### PR TITLE
Documentation/cahierdescharges

### PR DESCRIPTION
**Pull request by noahboegli**
New version of ""Cahier des charges""

This branche also removes
- Cahier des charges V1
- Cahier des charges V2
- Cahier des charges V1 - commented by JEB

If any of this is to be kept in master, simply revert the commit (and please move the docs in an `archive` directory)

### CODE REVIEW

**Comment by noahboegli** [comment]
@divad1196 
We have added 3 todos, I'll let you implement them (two of them are reviews of moved tasks between iterations, one is a list of tasks to add related to the restaurants part).

Once this is done, feel free to merge or ask for changes.

**Comment by dgheig** [comment]
## Wording
"a whatsapp group" -> "everlasting discussion on whatsapp groups"

## Objectives Part
First it adds something they do not provide (meal selection) then it adds features. This is not the other way around (order matters). We really need to be clear on that.
* the bullet point hasn't changed according to what was discussed
* the conclusion: I had to read 3 times to understand what was meant with the conclusion. 

## Other points
Ok for the diagram changes.

## TODOs
For the TODOs:
* User can add its own recipes (available for anyone): To be moved on the 2nd iteration to prioritize restaurant feature
* Add features for restaurant-meals: to be moved on the first iteration
* User can choose some meals and let the group vote: Ok to be moved

**Comment by noahboegli** [comment]
@dgheig 
I bumped the version number, since it seems ok for your I will now put everyone for review.

**Review by heigvdgachetje — APPROVED** [review]

**Comment by heigvdgachetje** [comment]
@noahboegli @dgheig 
I just realized that a section is missing in the cdc: Team members and role. To add before accepting PR.

**Comment by noahboegli** [comment]
@heigvdgachetje  I have added team members and roles (based on original version but with roles adapated)
Can you check ? 
Thanks !

**Review by dgheig — APPROVED** [review]

**Review by nigelmann — APPROVED** [review]

**Review by heigvdgachetje — APPROVED** [review]

**Review by HugoMendes98 — APPROVED** [review]

**Pull request merged**
