### PR TITLE
Documentation/{p2-39}-ea-model-refactor

### PR DESCRIPTION
**Pull request by heigvdgachetje**
Proposition of changes to the entity-association to reflect the need of some features in the application.

### CODE REVIEW

**Review by dgheig — APPROVED** [review]
Thank you for putting the changes in read, this is much appreciated.
I think every changes we discussed are present, I don't see anything that could be done differently either.

**Comment by fterrani** [comment]
Look good to me. Would it be possible to add a `Category` entity? This would allow to somewhat group food constraints in the formular and avoid having a bunch of checkboxes with sequences like vegan -> italian -> lactose free -> mexican -> no gluten -> chinese... which looks rather weird?

**Comment by heigvdgachetje** [comment]
> Look good to me. Would it be possible to add a `Category` entity? This would allow to somewhat group food constraints in the formular and avoid having a bunch of checkboxes with sequences like vegan -> italian -> lactose free -> mexican -> no gluten -> chinese... which looks rather weird?

@fterrani yes it's doable. Do you think an entity is necessary though? Would an extra attribute in the entity Food constraint be OK? For example a category field that would have to take values from an enumeration (allergy, intolerance, preference, ...)?

**Comment by fterrani** [comment]
@heigvdgachetje Sounds good to me, but I think we should confirm this with @nigelmann

**Comment by heigvdgachetje** [comment]
I added a `category` to the `food constraint` entity as proposed by @fterrani.
@dgheig can your review the new changes?
@nigelmann can you review the whole PR?
Thank you!

**Review by nigelmann — APPROVED** [review]

**Review by dgheig — APPROVED** [review]

**Pull request merged**
